name = "minigawa"
description = "A simple, minimal retro theme"
license = "MIT"
homepage = "https://github.com/bbjornstad/zola-theme-termigawa"
min_version = "0.11.0"

# An optional live demo URL
demo = "https://pawroman.github.io/zola-theme-terminimal/"

[author]
name = "Bailey Bjornstad"
homepage = "https://bjornstad.dev"

[original]
author = "Paweł Romanowski"
homepage = "https://github.com/pawroman"
repo = "https://github.com/pawroman/zola-theme-terminimal"

[extra]

# One of: blue, green, orange, pink, red.
accent_color = "blue"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "blue"

# The logo text - defaults to 2 non-breaking spaces.
logo_text = "Minigawa theme - terMinimal theme port with Kanagawa.nvim colors"

# Whether to show links to earlier and later posts
# on each post page.
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
post_view_navigation_prompt = "Other posts..."

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false
